management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/rrdbc
    username: root
    password: root

logging:
  level:
    org.springframework.r2dbc: TRACE
